[tool.robotpy]
robotpy_version = "2025.3.2.2"
requires = [
  "robotpy-commands-v2",
  "robotpy-rev",
  "robotpy-navx",
  "robotpy-pathplannerlib",
  "photonlibpy==2026.0.1-beta",
  "numpy==2.2.1.dev0; platform_machine == 'roborio'"
]